version: '3.8'

services:
  # Spring Boot application
  stayease:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stayease
      - SPRING_DATASOURCE_USERNAME=stayease_user
      - SPRING_DATASOURCE_PASSWORD=stayease_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db
    networks:
      - stayease-network

  # PostgreSQL database
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: stayease
      POSTGRES_USER: stayease_user
      POSTGRES_PASSWORD: stayease_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - stayease-network

volumes:
  postgres-data:

networks:
  stayease-network:
    driver: bridge
